#ifndef ERRORS
#define ERRORS

unsigned int GLOBAL_ERROR = 0;

#define DRIVER_CONNECTION_ERROR 1
#define DRIVER_DATA_ERROR 2
#define DRIVER_FATAL_ERROR 4
#define IMU_DATA_ERROR 8
#define IMU_CONNECTION_ERROR 16
#define LINE_BOARD_CONNECTION_ERROR 32
#define CAMERA_CONNECTION_ERROR 64
#define CAMERA_DATA_ERROR 128
#define LIDAR_DATA_ERROR 256
#define BALL_SENSOR_POWER_OFF 512
#define IMU_POWER_OFF 1024
#define LOW_BATTERY_POWER 2048

#endif
