#ifndef CONNECTION_LIST
#define CONNECTION_LIST


#define DEBUG_UART	_UART1					// DEBUG UART

#define LED	PB12					// LED

#define MOTHERBOARD_SPI	_SPI1				// MOTHERBOARD SPI (MOTHERBOARD IS MASTER)

#define SENSORS_POWER	PB13					// SENSORS POWER EN

#define MULTIFLEXER_1_OUTPUT	PA0			//MULTIFLEXERS OUTPUTS
#define MULTIFLEXER_2_OUTPUT	PA1
#define MULTIFLEXER_INPUT_1	PB10			//MULTIFLEXERS INPUTS
#define MULTIFLEXER_INPUT_2	PB2
#define MULTIFLEXER_INPUT_3	PB1
#define MULTIFLEXER_INPUT_4	PB11

#define CALIBRATION_START 0x01
#define CALIBRATION_END   0x02
#define SENSORS_ON 0x03
#define SENSORS_OFF   0x04

#endif
